config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions
  get 'report/reportlist'

  get 'report/custlist'

  get 'report/prodlist'

  get 'report/orderlist'

  resources :orderitems
  resources :ordertypes
  resources :itemtypes
  resources :genres
  resources :artists
  resources :albums
  resources :customers
  resources :orders
  resources :tracks
  root  'home#index'

  get 'home/about'

  get 'home/contact'

  get 'home/index'

  get 'home/privacy'

  get 'home/help'

  get 'home/legal'

  get 'home/search'
  post 'home/search'
  post 'home/buy'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions

  get 'home/catalog'
  post 'home/buy'
  post 'home/updatecart'
  post 'home/checkout'
  get 'cart', to: 'home#cart', as: 'cart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :albumname, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :artist_id, presence: true
  validates :albumprice, presence: true

  has_many :track, dependent: :destroy
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :artistname, presence: true
  validates :bio, presence: true
  validates :genre_id, presence: true

  has_many :track, dependent: :destroy
  has_many :album, dependent: :destroy
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :custfirstname, presence: true
  validates :custlastname, presence: true
  validates :custstreet, presence: true
  validates :custcity, presence: true
  validates :custstate, presence: true
  validates :custzip, presence: true

  validates :username, presence:true, uniqueness:true
  has_secure_password

  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genrename, presence: true

  has_many :artist
end

app/models/itemtype.rb
class Itemtype < ApplicationRecord
  validates :itemtypedescription, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :orderdate, presence: true
  validates :customer_id, presence: true
  validates :paymenttype, presence: true

  has_many :orderitem, dependent: :destroy
  belongs_to :customer
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  validates :order_id, presence: true
  validates :album_id, presence: true
  validates :track_id, presence: true
  validates :itemtype_id, presence: true
  validates :ordertype_id, presence: true
  validates :order_id, presence: true
end

app/models/ordertype.rb
class Ordertype < ApplicationRecord
  validates :ordertype, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  validates :trackname, presence: true
  validates :artist_id, presence: true
  validates :album_id, presence: true
  validates :trackprice, presence: true

  belongs_to :album
  belongs_to :artist
end

app/controllers/ordertypes_controller.rb
class OrdertypesController < ApplicationController
  before_action :set_ordertype, only: [:show, :edit, :update, :destroy]

  # GET /ordertypes
  # GET /ordertypes.json
  def index
    @ordertypes = Ordertype.all
  end

  # GET /ordertypes/1
  # GET /ordertypes/1.json
  def show
  end

  # GET /ordertypes/new
  def new
    @ordertype = Ordertype.new
  end

  # GET /ordertypes/1/edit
  def edit
  end

  # POST /ordertypes
  # POST /ordertypes.json
  def create
    @ordertype = Ordertype.new(ordertype_params)

    respond_to do |format|
      if @ordertype.save
        format.html { redirect_to @ordertype, notice: 'Ordertype was successfully created.' }
        format.json { render :show, status: :created, location: @ordertype }
      else
        format.html { render :new }
        format.json { render json: @ordertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordertypes/1
  # PATCH/PUT /ordertypes/1.json
  def update
    respond_to do |format|
      if @ordertype.update(ordertype_params)
        format.html { redirect_to @ordertype, notice: 'Ordertype was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordertype }
      else
        format.html { render :edit }
        format.json { render json: @ordertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordertypes/1
  # DELETE /ordertypes/1.json
  def destroy
    @ordertype.destroy
    respond_to do |format|
      format.html { redirect_to ordertypes_url, notice: 'Ordertype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordertype
      @ordertype = Ordertype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordertype_params
      params.require(:ordertype).permit(:ordertype)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itemtypes_helper.rb
module ItemtypesHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ordertypes_helper.rb
module OrdertypesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/ordertypes/_form.html.erb
<%= form_with(model: ordertype, local: true) do |form| %>
  <% if ordertype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordertype.errors.count, "error") %> prohibited this ordertype from being saved:</h2>

      <ul>
      <% ordertype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ordertype %>
    <%= form.text_field :ordertype, id: :ordertype_ordertype %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordertypes/edit.html.erb
<h1>Editing Ordertype</h1>

<%= render 'form', ordertype: @ordertype %>

<%= link_to 'Show', @ordertype %> |
<%= link_to 'Back', ordertypes_path %>

app/views/ordertypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordertypes</h1>

<table>
  <thead>
    <tr>
      <th>Ordertype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordertypes.each do |ordertype| %>
      <tr>
        <td><%= ordertype.ordertype %></td>
        <td><%= link_to 'Show', ordertype %></td>
        <td><%= link_to 'Edit', edit_ordertype_path(ordertype) %></td>
        <td><%= link_to 'Destroy', ordertype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordertype', new_ordertype_path %>

app/views/ordertypes/new.html.erb
<h1>New Ordertype</h1>

<%= render 'form', ordertype: @ordertype %>

<%= link_to 'Back', ordertypes_path %>

app/views/ordertypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ordertype:</strong>
  <%= @ordertype.ordertype %>
</p>

<%= link_to 'Edit', edit_ordertype_path(@ordertype) %> |
<%= link_to 'Back', ordertypes_path %>