config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions
  get 'report/reportlist'

  get 'report/custlist'

  get 'report/prodlist'

  get 'report/orderlist'

  resources :orderitems
  resources :ordertypes
  resources :itemtypes
  resources :genres
  resources :artists
  resources :albums
  resources :customers
  resources :orders
  resources :tracks
  root  'home#index'

  get 'home/about'

  get 'home/contact'

  get 'home/index'

  get 'home/privacy'

  get 'home/help'

  get 'home/legal'

  get 'home/search'
  post 'home/search'
  post 'home/buy'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions

  get 'home/catalog'
  post 'home/buy'
  post 'home/updatecart'
  post 'home/checkout'
  get 'cart', to: 'home#cart', as: 'cart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :albumname, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :artist_id, presence: true
  validates :albumprice, presence: true

  has_many :track, dependent: :destroy
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :artistname, presence: true
  validates :bio, presence: true
  validates :genre_id, presence: true

  has_many :track, dependent: :destroy
  has_many :album, dependent: :destroy
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :custfirstname, presence: true
  validates :custlastname, presence: true
  validates :custstreet, presence: true
  validates :custcity, presence: true
  validates :custstate, presence: true
  validates :custzip, presence: true

  validates :username, presence:true, uniqueness:true
  has_secure_password

  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genrename, presence: true

  has_many :artist
end

app/models/itemtype.rb
class Itemtype < ApplicationRecord
  validates :itemtypedescription, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :orderdate, presence: true
  validates :customer_id, presence: true
  validates :paymenttype, presence: true

  has_many :orderitem, dependent: :destroy
  belongs_to :customer
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  validates :order_id, presence: true
  validates :album_id, presence: true
  validates :track_id, presence: true
  validates :itemtype_id, presence: true
  validates :ordertype_id, presence: true
  validates :order_id, presence: true
end

app/models/ordertype.rb
class Ordertype < ApplicationRecord
  validates :ordertype, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  validates :trackname, presence: true
  validates :artist_id, presence: true
  validates :album_id, presence: true
  validates :trackprice, presence: true

  belongs_to :album
  belongs_to :artist
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize
  def about
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def catalog
    @prod = Track.all
  end

  def contact
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def index
    @time = Time.now
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def privacy
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def help
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def legal
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def buy
    @prodid = params[:prodid].to_i
    session[:cart_prod] << @prodid
    redirect_to cart_url
  end

  def cart
  end

  def updatecart
    cartid = params[:cartid].to_i;
    session[:cart_prod].delete_at(cartid)
    redirect_to cart_url
  end

  def checkout
    cartlen = session[:cart_prod].length
    i=0
    if cartlen > 0
      orderid = Order.create(customer_id: session[:user_id], orderdate: Date.today, paymenttype: "Online Order")
      while i < cartlen
  #      Orderitem.create(order_id: orderid.id, track_id: session[:cart_prod][i].to_i, saleprice: Track.find(session[:cart_prod][i].to_i).saleprice, prodqty: session[:cart_qty][i])
        i = i + 1
      end
      session[:cart_prod] = Array.new
      session[:cart_qty] = Array.new
    end
  end

  def search
    @results=0
    if !params[:searchinput].nil?
      @results=1
      @searchinput = params[:searchinput]
      @searchcriteria="%#{params[:searchinput]}%"
      @albumlist = Album.where("albumname like ? or description like ?",@searchcriteria, @searchcriteria)
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  skip_before_action :authorize , :only => [:show]
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
    @artist_choice = Artist.order("artistname").collect do |a| [a.artistname, a.id] end
    @album_choice = Album.order("albumname").collect do |b| [b.albumname, b.id] end
  end

  # GET /tracks/1/edit
  def edit
    @artist_choice = Artist.order("artistname").collect do |a| [a.artistname, a.id] end
    @album_choice = Album.order("albumname").collect do |b| [b.albumname, b.id] end
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)
    @artist_choice = Artist.order("artistname").collect do |a| [a.artistname, a.id] end
    @album_choice = Album.order("albumname").collect do |b| [b.albumname, b.id] end
    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:trackname, :artist_id, :album_id, :trackprice)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itemtypes_helper.rb
module ItemtypesHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ordertypes_helper.rb
module OrdertypesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :trackname %>
    <%= form.text_field :trackname, id: :track_trackname %>
  </div>

  <div class="field">
    <%= form.label :artist_id %>
    <%= form.select :artist_id, @artist_choice %>
  </div>

  <div class="field">
    <%= form.label :album_id %>
    <%= form.select :album_id, @album_choice %>
  </div>

  <div class="field">
    <%= form.label :trackprice %>
    <%= form.text_field :trackprice, id: :trackprice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Trackname</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Track Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.trackname %></td>
        <td><%= track.artist_id %></td>
        <td><%= track.album_id %></td>
        <td><%= track.trackprice %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trackname:</strong>
  <%= @track.trackname %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @track.artist_id %>
</p>

<p>
  <strong>Album:</strong>
  <%= @track.album_id %>
</p>

<p>
  <strong>Track Price:</strong>
  <%= @track.trackprice %>
</p>
<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>