config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions
  get 'report/reportlist'

  get 'report/custlist'

  get 'report/prodlist'

  get 'report/orderlist'

  resources :orderitems
  resources :ordertypes
  resources :itemtypes
  resources :genres
  resources :artists
  resources :albums
  resources :customers
  resources :orders
  resources :tracks
  root  'home#index'

  get 'home/about'

  get 'home/contact'

  get 'home/index'

  get 'home/privacy'

  get 'home/help'

  get 'home/legal'

  get 'home/search'
  post 'home/search'
  post 'home/buy'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions

  get 'home/catalog'
  post 'home/buy'
  post 'home/updatecart'
  post 'home/checkout'
  get 'cart', to: 'home#cart', as: 'cart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :albumname, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :artist_id, presence: true
  validates :albumprice, presence: true

  has_many :track, dependent: :destroy
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :artistname, presence: true
  validates :bio, presence: true
  validates :genre_id, presence: true

  has_many :track, dependent: :destroy
  has_many :album, dependent: :destroy
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :custfirstname, presence: true
  validates :custlastname, presence: true
  validates :custstreet, presence: true
  validates :custcity, presence: true
  validates :custstate, presence: true
  validates :custzip, presence: true

  validates :username, presence:true, uniqueness:true
  has_secure_password

  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genrename, presence: true

  has_many :artist
end

app/models/itemtype.rb
class Itemtype < ApplicationRecord
  validates :itemtypedescription, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :orderdate, presence: true
  validates :customer_id, presence: true
  validates :paymenttype, presence: true

  has_many :orderitem, dependent: :destroy
  belongs_to :customer
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  validates :order_id, presence: true
  validates :album_id, presence: true
  validates :track_id, presence: true
  validates :itemtype_id, presence: true
  validates :ordertype_id, presence: true
  validates :order_id, presence: true
end

app/models/ordertype.rb
class Ordertype < ApplicationRecord
  validates :ordertype, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  validates :trackname, presence: true
  validates :artist_id, presence: true
  validates :album_id, presence: true
  validates :trackprice, presence: true

  belongs_to :album
  belongs_to :artist
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authorize , :only => [:show]
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @genre_choice = Genre.order("genrename").collect do |a| [a.genrename, a.id] end
  end

  # GET /artists/1/edit
  def edit
    @genre_choice = Genre.order("genrename").collect do |a| [a.genrename, a.id] end
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:artistname, :bio, :genre_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize
  def about
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def catalog
    @prod = Track.all
  end

  def contact
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def index
    @time = Time.now
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def privacy
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def help
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def legal
    @promotions = Promotion.where("startdate <= ? AND enddate >= ?", Date.today, Date.today)
  end

  def buy
    @prodid = params[:prodid].to_i
    session[:cart_prod] << @prodid
    redirect_to cart_url
  end

  def cart
  end

  def updatecart
    cartid = params[:cartid].to_i;
    session[:cart_prod].delete_at(cartid)
    redirect_to cart_url
  end

  def checkout
    cartlen = session[:cart_prod].length
    i=0
    if cartlen > 0
      orderid = Order.create(customer_id: session[:user_id], orderdate: Date.today, paymenttype: "Online Order")
      while i < cartlen
  #      Orderitem.create(order_id: orderid.id, track_id: session[:cart_prod][i].to_i, saleprice: Track.find(session[:cart_prod][i].to_i).saleprice, prodqty: session[:cart_qty][i])
        i = i + 1
      end
      session[:cart_prod] = Array.new
      session[:cart_qty] = Array.new
    end
  end

  def search
    @results=0
    if !params[:searchinput].nil?
      @results=1
      @searchinput = params[:searchinput]
      @searchcriteria="%#{params[:searchinput]}%"
      @albumlist = Album.where("albumname like ? or description like ?",@searchcriteria, @searchcriteria)
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itemtypes_helper.rb
module ItemtypesHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ordertypes_helper.rb
module OrdertypesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artistname %>
    <%= form.text_field :artistname, id: :artist_artistname %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :artist_bio %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.select :genre_id, @genre_choice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Artistname</th>
      <th>Bio</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.artistname %></td>
        <td><%= artist.bio %></td>
        <td><%= artist.genre_id %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artistname:</strong>
  <%= @artist.artistname %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @artist.genre_id %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>