config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :promotions
  get 'report/reportlist'

  get 'report/custlist'

  get 'report/prodlist'

  get 'report/orderlist'

  resources :orderitems
  resources :ordertypes
  resources :itemtypes
  resources :genres
  resources :artists
  resources :albums
  resources :customers
  resources :orders
  resources :tracks
  root  'home#index'

  get 'home/about'

  get 'home/contact'

  get 'home/index'

  get 'home/privacy'

  get 'home/help'

  get 'home/legal'

  get 'home/search'
  post 'home/search'
  post 'home/buy'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions

  get 'home/catalog'
  post 'home/buy'
  post 'home/updatecart'
  post 'home/checkout'
  get 'cart', to: 'home#cart', as: 'cart'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :albumname, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :artist_id, presence: true
  validates :albumprice, presence: true

  has_many :track, dependent: :destroy
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :artistname, presence: true
  validates :bio, presence: true
  validates :genre_id, presence: true

  has_many :track, dependent: :destroy
  has_many :album, dependent: :destroy
  belongs_to :genre
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :custfirstname, presence: true
  validates :custlastname, presence: true
  validates :custstreet, presence: true
  validates :custcity, presence: true
  validates :custstate, presence: true
  validates :custzip, presence: true

  validates :username, presence:true, uniqueness:true
  has_secure_password

  has_many :order, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genrename, presence: true

  has_many :artist
end

app/models/itemtype.rb
class Itemtype < ApplicationRecord
  validates :itemtypedescription, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :orderdate, presence: true
  validates :customer_id, presence: true
  validates :paymenttype, presence: true

  has_many :orderitem, dependent: :destroy
  belongs_to :customer
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  validates :order_id, presence: true
  validates :album_id, presence: true
  validates :track_id, presence: true
  validates :itemtype_id, presence: true
  validates :ordertype_id, presence: true
  validates :order_id, presence: true
end

app/models/ordertype.rb
class Ordertype < ApplicationRecord
  validates :ordertype, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
  validates :trackname, presence: true
  validates :artist_id, presence: true
  validates :album_id, presence: true
  validates :trackprice, presence: true

  belongs_to :album
  belongs_to :artist
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itemtypes_helper.rb
module ItemtypesHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ordertypes_helper.rb
module OrdertypesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/_footer.html.erb
<div class="footer-grid">
  <div class="footerlogo"><%= link_to "small LOGO & link home", home_index_path %></div>
  <div class="copyright">Admin Pages: | <%= link_to "orderitems", orderitems_path %> | <%= link_to "ordertypes", ordertypes_path %> | <%= link_to "itemtypes", itemtypes_path %> | <%= link_to "genres", genres_path %> | <%= link_to "artists", artists_path %> | <%= link_to "albums", albums_path %> | <%= link_to "customers", customers_path %> | <%= link_to "orders", orders_path %> | <%= link_to "tracks", tracks_path %> | <br> |<%= link_to "help", home_help_path %> | <%= link_to "privacy policy ", home_privacy_path %> | <%= link_to "copyright & legal stuff", home_legal_path %> | </div>
</div>

app/views/layouts/_header.html.erb
<div class="header-grid">
  <div class="logo"><%=  image_tag("tempLogo2.jpg", align: 'left', size: "160x42" )%><%= link_to "Welcome to chiTunes", home_index_path %></div>
  <div class="about"><%= link_to "About chiTunes", home_about_path %></div>
  <div class="contact"><%= link_to "How to contact us", home_contact_path %></div>
  <div class="contact"><%= link_to "Catalog of Tracks", home_catalog_path %></div>
  <div class="contact">Artists link goes here</div>
  <div class="contact">Link</div>
  <div class="contact">Link</div>
  <div class="contact">link to profile</div>
  <div class="search"><%= form_tag :controller => 'home', :action => 'search' do %>
      <%= text_field_tag 'searchinput', @searchinput, options = {style:"height:100%;border-radius:5px;width:100%;", placeholder:"Enter search terms, press enter tp search........"} %> </p>
    <% end %></div>
  <div class="hello">
    <% if session[:user_id].nil? %>
      <%= link_to "Create Account", new_customer_path %>
    <% else %>
      Hello <%= Customer.find(session[:user_id]).username %> !
    <% end %>
    </div>
  <div class="login">
    <% if session[:user_id].nil? %>
      <%= link_to "Login", login_path, :method => :get %>
    <% else %>
      <%= link_to "Logout", logout_path, :method => :delete %>
    <% end %>
    </div>
  <div class="feature3"><%= link_to "Reports", report_reportlist_path %></div>
  <div class="feature4">feature item</div>
  <div class="feature4">feature item</div>
  <div class="feature4">feature item</div>
  <div class="feature4">feature item</div>
  <div class="feature4">feature item</div>
  <div class="feature4">feature item</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChiTunesBeta1</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body style="background-color: #b3ddf2">
<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>